import Head from "next/head";
import Layout from "@/components/Layout";
// import Hero from '@/components/mobilbekas/index'
import TabsComponent from "@/components/tabs/TabsComponent";
import MobilBekas from "@/components/mobilbekas/index";
import { useRouter } from "next/router";
import MobilBekasComponent from "@/components/mobilbekas/index";
import { listMobil } from "@/data/data";
import { Typography } from "@mui/material";

export default function MobilDetail() {
  const router = useRouter();

  const { namaMobil } = router.query;

  const item = listMobil.find((item) => item.namaMobil === namaMobil);

  // console.log(item);

  // if (!item) {
  //   return <p>Not found</p>;
  // }

  return (
    <Layout>
      <Head>
        <title>Beli Mobil Bekas terbaik di Batam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {item ? (
        <MobilBekasComponent
          namaMobil={item.namaMobil}
          harga={item.harga}
          judulDeskripsi={item.deskripsi.judul}
          listDeskripsi={item.deskripsi.detail}
          listGambar={item.deskripsi.gambarDetail}
        />
      ) : (
        <Typography variant="body1" component={"p"}>Loading...</Typography>
      )}

      {/* <MobilBekasComponent {...item} /> */}
    </Layout>
  );
}
